version: '3.4'

services:
  netseven_test:
    image: api
    build:
      context: .
      dockerfile: src/netseven_test/Dockerfile
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=https://+:443;http://+:80
      - REDIS_CONNECTION=redis:6379,password=password
    ports:
      - "80"
      - "443"
  redis:
    image: redis
    ports:
      - "6379"
    command: redis-server --requirepass password

